export const injectTokens = {
  WorldsTimeScale: "WorldsTimeScale",
  ActorsContainer: "ActorsContainer",
  ActorsTimeScale: "ActorsTimeScale",
  ActorsMover: "ActorsMover",
  ActorsOverlapChecker: "ActorsOverlapChecker",
  Renderer: "Renderer",
  WorldsExtensionUpdater: "WorldsExtensionUpdater",
  ActorsExtensionUpdater: "ActorsExtensionUpdater",
  WorldsTimerUpdater: "worldsTimerUpdater",
  ActorsTimerUpdater: "actorsTimerUpdater",
  InputConsumer: "InputConsumer",
  WorldsUpdateEventEmitter: "WorldsUpdateEventEmitter",
  ActorsUpdateEventEmitter: "ActorsUpdateEventEmitter",
} as const;
