export const injectTokens = {
  DIContainer: "DIContainer",
  Actor: "Actor",
  ActorCreateUC: "DestroyActorUC",
  UpdateActorUC: "UpdateActorUC",
  CollisionModifyUC: "CollisionModifyUC",
  CollisionManipulationUC: "CollisionManipulationUC",
  ActorAddingToWorldUC: "ActorAddingToWorldUC",
  UpdateWorldUC: "UpdateWorldUC",
  CreateWorldUC: "CreateWorldUC",
  World: "World",
  EngineCreationUC: "EngineCreationUC",
  RegisterRendererUC: "RegisterRendererUC",
  WorldUpdatingInEngineUC: "WorldUpdatingInEngineUC",
  EngineInput: "EngineInput",
} as const;
